# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

